### ISSUE TITLE
How to use field node source_service  option on system.xml ?

### ISSUE THREAD

**Issue by mandrills** [AdobeDocs/commerce-operations.en#107]
## Topic Link

https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/files/config-reference-systemxml.html?lang=en

## Description

In the official documentation, the `field` node has `source_service`, but there is no example of how to use it, and there is no place for using it in the framework vendor. How to use this?

![image](https://github.com/AdobeDocs/commerce-operations.en/assets/14126358/b473aeb2-da40-4556-8a1b-a8d8b6364768)

**Comment by TuVanDev** [comment]
The `source_service` field node was first introduced as part of the **Service Calls Framework** in the Magento version `2.0.0.0-dev45` in 2013.
The following are excerpts from the [CHANGELOG.md](https://github.com/magento/magento2/blob/2.4.6-p2/CHANGELOG.md) file.

> * Various improvements:
>   * Refactored experimental implementation of Service Calls Framework
>      * All code from to `lib/Magento/Datasource` and `app/code/Mage/Core/Datasource` moved to `app/code/Mage/Core/DataService`
>      * Added service calls support in Layout model
>      * Fixed bugs and architectural flaws
>      * Changed service calls declaration
>      * Improved test coverage
>      * Introduced mechanism to retrieve values from nested arrays by path
>      * Added Invoker class to invoke service calls by given name
>      * Added ability to define system configuration options via service calls. Refactored implementation for select field in XML

Related commit: https://github.com/magento/magento2/commit/a15ecb31976feb4ecb62f85257ff6b606fbdbc00

The **Service Calls Framework** in Magento was removed since the Magento version `2.0.0.0-dev62` in 2014.
The following is an excerpt from the [CHANGELOG.md](https://github.com/magento/magento2/blob/2.4.6-p2/CHANGELOG.md) file.

> * Removed the deprecated service-calls and data source functionality

Related commit: https://github.com/magento/magento2/commit/8f72656ff34b751fae5227481de836f269f52270

As a result, the `source_service` field node is no longer used.
