### ISSUE TITLE
db_schema.xml file, column type is int type,  padding attribute not working

### ISSUE THREAD

**Issue by mandrills** [AdobeDocs/commerce-operations.en#111]
## Description

In the db_schema.xml file, when the field is set to int type, the padding attribute set after executing the command does not working

## Content checklist

Add an int type field to a table and set the padding attribute. After running the setup:upgrade command, I found that the padding attribute was ignored and had no effect.

## Additional information

The file we refer to for setting attributes is the official Magento xsd file:

```vendor/magento/framework/Setup/Declaration/Schema/etc/types/integers/integer.xsd```

**Comment by jeff-matthews** [comment]
@mandrills

It doesn't appear that your issue is related to the docs. You might have better luck searching the [magento/magento2](https://github.com/magento/magento2) repo or [magento.stackexchange.com](https://magento.stackexchange.com/).

You may also want to review this page in the docs about [Removed width for integer types (padding)](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/database-server/mysql.html?lang=en#removed-width-for-integer-types-(padding)).
